application: giltregrouper
version: beta
runtime: java


handlers:
- url: /api/brands
  name: BrandsServlet
  servlet: com.thepoofy.gilt.servlet.BrandsServlet
- url: /api/categories
  name: CategoriesServlet
  servlet: com.thepoofy.gilt.servlet.CategoriesServlet
- url: /api/products
  name: ProductsServlet
  servlet: com.thepoofy.gilt.servlet.ProductsServlet



- url: /tasks/*
  login: admin

- url: /tasks/update_sales
  name: UpdateSalesServlet
  servlet: com.thepoofy.gilt.servlet.tasks.UpdateSalesServlet


threadsafe: true

welcome_files:
  - index.html

static_files:
  - include: /**.png
  - include: /**.css
  - include: /**.js
  - include: /**.html
  
