application: giltregrouper
version: beta3
runtime: java


handlers:
- url: /api/sites
  name: GiltSitesServlet
  servlet: com.thepoofy.gilt.servlet.GiltSitesServlet
- url: /api/brands
  name: BrandsServlet
  servlet: com.thepoofy.gilt.servlet.BrandsServlet
- url: /api/categories
  name: CategoriesServlet
  servlet: com.thepoofy.gilt.servlet.CategoriesServlet
- url: /api/products
  name: ProductsServlet
  servlet: com.thepoofy.gilt.servlet.ProductsServlet



- url: /tasks/*
  login: admin
  
- url: /tasks/update_cache
  name: UpdateCacheServlet
  servlet: com.thepoofy.gilt.servlet.tasks.UpdateCacheServlet

- url: /tasks/update_sale
  name: UpdateSalesServlet
  servlet: com.thepoofy.gilt.servlet.tasks.UpdateSaleServlet


threadsafe: true

welcome_files:
  - index.html

static_files:
  - include: /**.png
  - include: /**.css
  - include: /**.js
  - include: /**.html
  
